### PR TITLE
Add support for downloading files

### PR DESCRIPTION
**Pull request by jonahweissman**
Here is a pretty rough draft of my implementation of downloading files.

Still to be addressed:
- [x] What happens for datatypes that are not a single file (e.g. extracellular-arfdir)? returns 415 media type unsupported 
- [x] Should I add a key to the resource detail view to make the download link discoverable? I think I probably should, but I'm not sure if this should be added to the serializer or by overriding some methods on the view. (Or maybe we don't want this feature to be discoverable, to reduce the likelihood of having modified versions of resources floating around.)
- [x] Is there a more appropriate place than the Location model for the logic to use an archive scheme to create a path? Yes, switched to using nbank package
- [x] better error handling (e.g. file not found)
- [x] Right now, I try sending a resource from the first archive that it's present in that has a supported scheme, but maybe there is a more intelligent way to pick which archive to use? Current solution is fine because we are not considering cases with resources in multiple archives right now.
- [x] tests
- [ ] make sure that it works as expected with nginx (so far I have only used the sendfile development backend)

### CODE REVIEW

**Comment by dmeliza** [comment]
This looks promising! My thoughts on your queries (many-to-many mapping, so I'm just slapping them all together):

One idea would be to only serve single-file resources for now. That's the preferred way to package data anyway. In that case, it would make sense to add a field to the detail view that shows a link, but only if the server supports that kind of dtype and has access to the archive. You could check for this whenever someone accesses the detail view, which would mean only handling a small number of these lookups at a time. Otherwise when someone hits the download endpoint for a nonexistent file, I would think you'd just return a 404 or whatever code is most appropriate.

For finding resources, we may want to import the neurobank package (the one that includes the CLI and the Python API for interacting with the registry). It's sort of a circular dependency, though.

Probably the first match is fine for deciding what copy to return if there are more than one. I think the cases of resources being in multiple locations are small to nonexistent.

**Comment by jonahweissman** [comment]
I spent a little bit of time on this and added some basic tests, but I need some help on a few points.

> One idea would be to only serve single-file resources for now. That's the preferred way to package data anyway. 

I think this makes sense. Would it be okay if I added a boolean "downloadable" field to the Datatype model? I think I would make it default to false and then we can go back in and manually turn it on for the datatypes for which that makes sense. 

> In that case, it would make sense to add a field to the detail view that shows a link, but only if the server supports that kind of dtype and has access to the archive. You could check for this whenever someone accesses the detail view, which would mean only handling a small number of these lookups at a time. Otherwise when someone hits the download endpoint for a nonexistent file, I would think you'd just return a 404 or whatever code is most appropriate.

I think this is pretty reasonable. What do you mean by "has access to the archive"? Should I just check to see if the file exists or is there a more clever way?

> For finding resources, we may want to import the neurobank package (the one that includes the CLI and the Python API for interacting with the registry). It's sort of a circular dependency, though.

Unless we want to specify the API (which is not worth the trouble IMO), the two are kind of coupled anyway, so I think this would be okay. I think I might have mentioned this earlier, but python has trouble with the token `neurobank` when both are installed because it's the package name of the client and the root module name (not quite sure about the terminology here) of `django-neurobank`.

**Comment by dmeliza** [comment]
Yes to adding a downloadable field to the Datatype model.

Yes to just checking whether the file exists and returning a 404 if it does not.

Let's rename the root package in `django-neurobank` to something like `nbank_registry` to eliminate the name collision. We'll have to update `settings.py` and possibly some other spots in our `lab_internal_site` repo, but this way none of the code that uses `neurobank` will be affected.

**Comment by jonahweissman** [comment]
> Let's rename the root package in `django-neurobank` to something like `nbank_registry` to eliminate the name collision. We'll have to update `settings.py` and possibly some other spots in our `lab_internal_site` repo, but this way none of the code that uses `neurobank` will be affected.

Sounds good. Do you want me to fork `lab_internal_site` on gitolite and update it with the renamed package?

**Comment by dmeliza** [comment]
You should have write access to the main `lab_internal_site` repo so no need to fork. I can show you how to deploy if it's not obvious.

**Pull request merged**
